import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import Footer from "@/components/Footer/footer";
import "./globals.css";

import { prisma } from "@/lib/prisma";
import { cache } from "react";

import { FilterProvider } from "@/context/FilterContext";
import generateUniqParams from "@/utils/generateUniqFilterParams";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getData = cache(async () => {
  try {
    const response = await prisma.event.findMany({
      include: {
        place: true,
      },
    });

    return response;
  } catch (error) {
    return [];
  }
});

const Header = () => {
  return (
    <header className="w-full border-b border-border bg-brand text-surface">
      <div className="mx-auto flex h-16 w-full max-w-340 items-center justify-between px-4 sm:px-8">
        <Link href="/" className="flex items-center">
          <Image
            src="/logo.svg"
            alt="TicketHub logo"
            width={196}
            height={48}
            priority
            className="h-8 w-auto sm:h-10"
          />
        </Link>
      </div>
    </header>
  );
};

export default async function RootLayout({ children }) {
  const data = await getData();
  const propData = generateUniqParams(data);

  return (
    <html lang="cs" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-screen flex flex-col">
        <FilterProvider value={{ uniqParams: propData }}>
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </FilterProvider>
      </body>
    </html>
  );
}
