import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  return (
    <header className="w-full border-b border-border bg-brand text-surface">
      <div className="mx-auto flex h-16 w-full max-w-340 items-center justify-between px-4 sm:px-8">
        <Link href="/" className="flex items-center">
          <Image
            src="/logo.svg"
            alt="TicketHub logo"
            width={196}
            height={48}
            priority
            className="h-8 w-auto sm:h-10"
          />
        </Link>
      </div>
    </header>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
